CREATE TABLE "Customers" (
  "customer_id" integer PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "full_name" varchar(255) NOT NULL,
  "phone_number" varchar(20),
  "gender" varchar(10),
  "date_of_birth" date,
  "status" varchar(20) DEFAULT 'active',
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "Products" (
  "product_id" SERIAL PRIMARY KEY,
  "category_id" int NOT NULL,
  "sku" varchar(100) UNIQUE NOT NULL,
  "product_name" varchar(255) NOT NULL,
  "description" text,
  "price" decimal(12,2) NOT NULL,
  "stock_quantity" int NOT NULL DEFAULT 0,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "Category" (
  "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar NOT NULL,
  "description" text,
  "created_at" timestamp
);

CREATE TABLE "Orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int NOT NULL,
  "order_status" varchar(30) NOT NULL DEFAULT 'pending',
  "total_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "shipping_address" text NOT NULL,
  "payment_method" varchar(225),
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "Order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL DEFAULT 1,
  "unit_price" decimal(12,2) NOT NULL,
  "total_amount" decimal(12,2)
);

CREATE TABLE "Payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "payment_method" varchar(50) NOT NULL,
  "payment_status" varchar(100) NOT NULL DEFAULT 'pending',
  "transaction_id" varchar,
  "total_amount" decimal(12,2) NOT NULL,
  "paid_at" timestamp,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "Order_status" (
  "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "status" varchar NOT NULL,
  "notes" text,
  "changed_by" varchar DEFAULT 'System',
  "created_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "Products" ADD FOREIGN KEY ("category_id") REFERENCES "Category" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Customers" ADD FOREIGN KEY ("customer_id") REFERENCES "Products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Orders" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Order_items" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Order_items" ADD FOREIGN KEY ("product_id") REFERENCES "Products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Payments" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Order_status" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;
